/**
 * Projects showcase — the single source of truth for the cinematic Projects
 * interior (components/home/ProjectsInterior.tsx) and the crawlable SEO copy
 * (components/home/SeoContent.tsx). Update content here; the UI reads the array.
 *
 * MEDIA (every project has a viewport reserved for it):
 *   Drop a file into /public/projects and point `media` at it. Video wins over
 *   image; a poster shows before the video loads. A missing file degrades to a
 *   tasteful gradient placeholder (the panel never shows a broken <img>/<video>).
 *   Examples for id "helix":
 *     media: { image: '/projects/helix.jpg' }
 *     media: { video: '/projects/helix.mp4', poster: '/projects/helix.jpg' }
 *
 * LINKS: `live` / `source` / `play` render as CTA buttons. A private project
 *   (`private: true`) shows no external links — story only.
 */

export interface ProjectMedia {
  /** Screenshot / still under /public/projects (e.g. '/projects/helix.jpg'). */
  image?: string;
  /** Looping clip (mp4/webm) under /public/projects. Takes priority over image. */
  video?: string;
  /** Poster frame shown before/without the video. */
  poster?: string;
}

export interface ProjectLinks {
  /** "Live" — the deployed site. */
  live?: string;
  /** "Source" — the public repo. */
  source?: string;
  /** "Play" — an in-app demo route (e.g. '/arcade'). */
  play?: string;
}

export interface Project {
  /** Stable id; also the suggested media filename stem under /public/projects. */
  id: string;
  /** Human-readable name (serif heading on the panel). */
  name: string;
  /** Machine codename shown in the mono eyebrow (e.g. "HELIX"). */
  codename: string;
  /** One-line positioning statement. */
  tagline: string;
  /** 2-3 sentence story: problem → what I built → result. */
  story: string;
  /** Short "spec sheet" facts (mono), the impressive bullet points. */
  highlights: string[];
  /** Tech names; matched to brand glyphs in lib/tech-icons.ts (text chip if none). */
  tech: string[];
  /** The reserved media viewport content (image / video / poster). Optional. */
  media?: ProjectMedia;
  /** CTA links. Omitted entirely for a private build. */
  links?: ProjectLinks;
  /** Accent colour (hex) for the panel's glow + tech glyphs. */
  accent: string;
  /** Private build — render the story + stack but no external links. */
  private?: boolean;
}

export const projects: Project[] = [
  {
    id: 'helix',
    name: 'Helix',
    codename: 'HELIX',
    tagline: 'A local-first AI assistant that wakes to your voice and remembers.',
    story:
      'My flagship build: a personal AI assistant that runs entirely on my own laptop. It wakes on a spoken word, thinks with Claude, replies in a calm British voice, and runs a team of six background agents. Its defining feature is an intelligent memory that decides what is worth remembering, forgets gracefully over time, and renders everything it knows as a live 3D neural brain you can fly through.',
    highlights: [
      'Runs fully local on a 4 GB-VRAM laptop',
      'Intelligent 3-layer memory + live 3D brain',
      '243 passing tests · security-first, secrets never on disk',
    ],
    tech: ['Python', 'FastAPI', 'Claude', 'Tauri', 'React', 'TypeScript', 'Three.js'],
    // media: { video: '/projects/helix.mp4', poster: '/projects/helix.jpg' },
    accent: '#7fdfff',
    private: true,
  },
  {
    id: 'gdg-quantum',
    name: 'GDG Quantum',
    codename: 'GDG-QUANTUM',
    tagline: 'The cinematic WebGL site you are flying through right now.',
    story:
      'This site. A single-page experience built around a live 3D orb you navigate by diving into it, with a full WebGL world and a hidden browser game one click away. The hard part was making it cinematic AND fast AND accessible AND working on phones, all at once, while keeping the homepage under 100 kB.',
    highlights: [
      'Under 100 kB First Load on every device',
      'WebGL world + a whole game, async-isolated',
      'Nonce-CSP, WCAG AA, SEO-hardened',
    ],
    tech: ['Next.js', 'TypeScript', 'Three.js', 'GSAP', 'Tailwind CSS', 'Prisma', 'PostgreSQL'],
    // media: { image: '/projects/gdg-quantum.jpg' },
    links: {
      live: 'https://gdgquantum.com',
      source: 'https://github.com/GDGuzman11/GDGQuantumWeb',
    },
    accent: '#6ea8ff',
  },
  {
    id: 'starshell',
    name: 'Starshell',
    codename: 'STARSHELL',
    tagline: "A '93-pixel first-person shooter built in the browser, no game engine.",
    story:
      'A retro FPS I wrote from scratch on Three.js: the renderer, the physics, the hitscan combat, and a squad-coordinated alien AI that flanks, climbs, and zeroes in on you. There are zero asset files. Every texture and sound is generated by code at runtime. It is a full 20-level campaign that runs on a phone.',
    highlights: [
      'No game engine, zero asset files',
      'Squad AI: line-of-sight, flanking, climbing',
      '20-level campaign · ~288 kB, runs on mobile',
    ],
    tech: ['Three.js', 'TypeScript', 'Tailwind CSS', 'Web Audio'],
    // media: { video: '/projects/starshell.mp4', poster: '/projects/starshell.jpg' },
    links: {
      play: '/arcade',
      source: 'https://github.com/GDGuzman11/Starshell',
    },
    accent: '#ffd27a',
  },
];
